from pathlib import Path
import re
p=Path('C:/Users/21102/vtouch-project/clients/vtouch_onefile_example.js')
s=p.read_text()
start='''VTouch.prototype.startService=function(){if(this.serviceStarted)return this;this.serviceShell=new Shell(true);var base="/data/local/tmp/vtouch-runtime",cmd="M=/data/local/tmp/vtouchmerge;W=/data/local/tmp/vtouchws;B="+base+";S=$B/merge.sock;P=$B/merge.pid;Q=$B/websocket.pid;mkdir -p $B||exit 1;if [ -S $S ]&&[ -f $P ]&&[ -f $Q ];then mp=$(cat $P);wp=$(cat $Q);kill -0 $mp 2>/dev/null&&kill -0 $wp 2>/dev/null&&exit 0;fi;killall vtouchmerge 2>/dev/null;killall vtouchws 2>/dev/null;rm -f $S $P $Q;nohup $M -s $S -v 10 -w "+this.width+" -h "+this.height+" >/dev/null 2>&1 </dev/null & echo $!>$P;nohup $W >/dev/null 2>&1 </dev/null & echo $!>$Q";this.serviceShell.exec(cmd);this.serviceStarted=true;return this};'''
s,n=re.subn(r'VTouch\.prototype\.startService=.*?(?=\nVTouch\.prototype\.stopService=)',start,s,count=1,flags=re.S)
if n!=1: raise SystemExit('start not found')
connect='''VTouch.prototype.connect=function(onReady){var self=this,startedAt=Date.now();this.onReady=onReady||null;this.closed=false;this.connectAttempts=0;function attempt(){if(self.closed)return;self.connectAttempts++;log("[vtouch] connecting: "+self.url+" attempt="+self.connectAttempts);self.ws=new WebSocket(self.url);self.ws.on(WebSocket.EVENT_OPEN,function(){self.opened=true;self.closed=false;log("[vtouch] connected: "+(Date.now()-startedAt)+"ms");self._next();if(typeof self.onReady==="function")self.onReady(self)}).on(WebSocket.EVENT_MESSAGE,function(message){log("[vtouch] message: "+message)}).on(WebSocket.EVENT_TEXT,function(text){var response=String(text);log("[vtouch] <- "+response);if(response.indexOf("err")===0)log("[vtouch] server error: "+response)}).on(WebSocket.EVENT_BYTES,function(bytes){log("[vtouch] bytes: "+bytes.utf8())}).on(WebSocket.EVENT_CLOSING,function(code,reason){log("[vtouch] closing: "+code+" "+reason)}).on(WebSocket.EVENT_CLOSED,function(code,reason){self.opened=false;self.busy=false;self._clearReplyTimer();log("[vtouch] closed: "+code+" "+reason);if(!self.closed&&self.connectAttempts<50)self.retryTimer=setTimeout(attempt,100)}).on(WebSocket.EVENT_FAILURE,function(error){log("[vtouch] failure: "+error);if(!self.closed&&self.connectAttempts<50)self.retryTimer=setTimeout(attempt,100)})}attempt();events.on("exit",function(){try{self.close()}finally{try{self.stopService()}catch(error){log("[vtouch] stop service failed: "+error)}}});return this};'''
s,n=re.subn(r'VTouch\.prototype\.connect=.*?(?=\nVTouch\.prototype\._clearReplyTimer=)',connect,s,count=1,flags=re.S)
if n!=1: raise SystemExit('connect not found')
p.write_text(s)
print('rewritten')
