# -*- coding: utf-8 -*-
"""函数文档数据（Doxygen 风格）：由 build/_apply_funcdoc.py 注入到 src/*.c 的定义处与 vt_internal.h 的原型处。
字段：brief 一句话；params [(名字, 说明)]；ret 返回值语义；note 线程/调用时机/陷阱。"""

DOCS = {
# ---------------- §2 小工具 ----------------
"parse_long": dict(brief="把字符串解析成 [lo, hi] 区间内的整数（命令参数解析用）。",
    params=[("s", "待解析文本"), ("lo", "允许下界（含）"), ("hi", "允许上界（含）"), ("out", "成功时写入结果")],
    ret="0 成功；-1 非数字、越界或带多余字符。",
    note="范围检查就是协议的一部分：越界一律回 err，不静默截断。"),
"bit": dict(brief="取位图（cap_* 那几张能力位图）里的第 n 位。",
    params=[("b", "位图数组"), ("n", "位号")], ret="非 0 表示该位置位。"),
"logical_to_raw": dict(brief="逻辑坐标（设备像素）→ 触摸屏 raw 坐标。",
    params=[("logical", "逻辑值"), ("axis", "0=X 1=Y"), ("raw", "输出 raw 值")],
    ret="0 成功；-1 轴非法或该轴量程为 0。"),
"raw_to_logical": dict(brief="raw 坐标 → 逻辑坐标（转发区域事件时用）。",
    params=[("raw", "raw 值"), ("axis", "0=X 1=Y"), ("logical", "输出逻辑值")], ret="0 成功；-1 轴非法或量程非法。"),
"now_ns": dict(brief="单调时钟（纳秒），事件时间戳用。", ret="单调递增的纳秒数（CLOCK_MONOTONIC）。"),

# ---------------- §3+§4 队列 ----------------
"queue_drop_log": dict(brief="队列丢弃的诊断日志：前 3 次每次都打，之后每 100 次打一行。",
    params=[("what", "队列名（\"事件\" / \"出站\"）"), ("n", "该队列累计丢弃数")],
    note="诊断不占热路径（代价只是一次取模比较）。"),
"vtq_push": dict(brief="事件入队（单生产者 = 主线程，消费者 = 区域线程）。",
    params=[("q", "队列"), ("ev", "事件（按值拷入）")],
    note="永不阻塞、永不失败：队满先尝试把队尾同槽同类 move 原地合并，仍满则丢最旧（CAS 推 head，因为消费者也在推它）。"
         "消费端最多少收一条事件，注入路径不受影响。"),
"vtq_pop": dict(brief="事件出队（单消费者 = 区域线程）。", params=[("q", "队列"), ("ev", "输出事件")], ret="1 取到；0 队空。"),
"outq_reset": dict(brief="清空出站队列（新客户端接入 / 断连时）。", note="残包不许串给下一个客户端（§4.6）。"),
"outq_pending": dict(brief="出站队列是否非空（主循环据此决定要不要挂 POLLOUT）。", ret="1 有；0 无。"),
"outq_push": dict(brief="把一段**已经成帧的字节**放入出站队列（生产者 = 主线程 / 区域线程，一把短锁只包住一次 memcpy）。",
    params=[("p", "数据"), ("n", "长度")], note="队满丢最旧；文本请用 outq_push_text，不要直接调这个。"),
"outq_push_text": dict(brief="把一行文本按 WS 文本帧（未加掩码）补齐帧头后入队。", params=[("s", "文本"), ("n", "长度")],
    note="成帧必须在这一层做 —— 队列里存的就是完整帧，刷出端只负责写字节。漏了这步的症状：客户端收到裸文本、"
         "一帧都解不出来，而注入照常生效（所以最难发现）。"),
"outq_flush": dict(brief="主循环唯一的刷出点：socket 可写才写，写不完留到下次；真错（EPIPE/ECONNRESET）才踢客户端。",
    note="客户端 socket 是非阻塞的，这里绝不阻塞主线程。"),

# ---------------- §5+§6 区域 ----------------
"regions_clear": dict(brief="清空区域表，并把代次 +1（让区域线程重置它私有的状态表）。"),
"region_add": dict(brief="新增或覆盖一个区域（主线程持 region_lock 写表）。",
    params=[("id", "区域名（≤ REGION_ID_MAX 字符）"), ("type", "0=矩形 1=圆"), ("a1", "矩形 x1 / 圆 cx"),
            ("a2", "矩形 y1 / 圆 cy"), ("a3", "矩形 x2 / 圆 r"), ("a4", "矩形 y2"), ("enabled", "1 启用 0 禁用")],
    ret="0 成功；-1 参数非法、id 去重失败或表满。", note="几何合法性（是否超出逻辑尺寸等）也在这里判。"),
"region_hit": dict(brief="点是否落在区域内（矩形含边界；圆按半径平方比较）。",
    params=[("rg", "区域"), ("lx", "逻辑 x"), ("ly", "逻辑 y")], ret="1 命中；0 未命中。"),
"region_ev_send": dict(brief="发一条区域事件：订了 region 通道才入出站队列，没订就只打 (UNSUB) 日志。",
    params=[("id", "区域名"), ("ev", "down/enter/move/exit/up"), ("slot", "物理槽号"),
            ("lx", "逻辑 x"), ("ly", "逻辑 y"),
            ("ts_mono", "事件时间戳（单调钟纳秒；发出去时换算成墙钟毫秒）")],
    note="低频事件；只报物理手指。报文末尾带 <ms>：事件发生的墙钟毫秒（与脚本 Date.now() 同基准），由 ts_mono 换算而来 —— 脚本算按压时长/防抖/看延迟用它。"),
"region_apply": dict(brief="五事件判定（区域线程）：按本轮事件更新 slot_in/slot_hit/slot_last，并决定发哪条事件。",
    params=[("ev", "来自 region_q 的事件")],
    note="三张状态表是线程私有的，只在 region_lock 里读区域表。"),
"region_thread_main": dict(brief="区域线程主循环：pop region_q → region_apply；区域表代次变了就重置私有状态。",
    params=[("arg", "未使用")], ret="NULL（线程不主动退出）。",
    note="只消费队列、只写自己的状态表、只往出站队列塞 region_ev；绝不注入、绝不直写 socket、绝不碰 phys[]/virt[]。"),

# ---------------- §7 物理输入 ----------------
"validate_device": dict(brief="认一块设备是不是 Type-B 触摸屏（槽 + tracking id + XY 四轴 + 量程），"
                             "并把它的能力声明整份抄进 cap_*（供 setup_uinput 镜像）。",
    params=[("p", "设备节点路径"), ("slots", "输出物理槽数"), ("xmin", "输出 X 下界"), ("xmax", "输出 X 上界"),
            ("ymin", "输出 Y 下界"), ("ymax", "输出 Y 上界")], ret="0 是；-1 不是或打不开。",
    note="不写死 eventN：由 discover 扫 event0..63 逐个问。"),
"discover": dict(brief="扫 /dev/input/event0..63，找第一块 Type-B 触摸屏。",
    params=[("out", "输出设备节点路径"), ("n", "缓冲长度")], ret="0 找到；-1 没找到。"),
"setup_uinput": dict(brief="建合并 uinput 设备：照抄物理屏的能力（EV / KEY / ABS+absinfo / props），"
                          "只改 4 处真冲突（TOOL_TYPE 量程、槽数、tracking id 量程、名字与 bus），并强制 INPUT_PROP_DIRECT。",
    ret="0 成功；-1 失败（调用方以退出码 3 退出）。",
    note="槽数 = phys_slots + vslots；tracking id 上限 = total_slots - 1。名字加 _vtouch 后缀，避免与物理设备同名。"),
"physical_events": dict(brief="读物理流：解析 Type-B 事件进 phys[]（按槽），在 SYN_REPORT 处提交一帧并转发。",
    note="一次 read 可能攒好几帧，边沿在每帧处理完就清；SYN_DROPPED 保守地把所有槽当抬起。"),

# ---------------- §8+§9 组帧 / 合帧 / 转发 ----------------
"ev_add": dict(brief="往本帧的 iovec 里追加一条 input_event（纯内存，不做系统调用）。",
    params=[("t", "事件类型"), ("c", "事件码"), ("v", "值")], note="上限 MAX_IOV，超出直接忽略。"),
"uinput_writev_retry": dict(brief="把当前帧一次 writev 写进 uinput；EAGAIN 时等最多 3×20ms 再试。",
    ret="实际写出的字节数；-1 真错。", note="uinput 是以 O_NONBLOCK 打开的。"),
"emit_iov_writev": dict(brief="提交本帧；**短写要把剩下的 iovec 补完**（只补一条会丢帧尾的 SYN_REPORT，系统里就成了半帧）。",
    ret="0 成功；-1 失败。"),
"any_emitted": dict(brief="本帧是否真的发了触点（决定 BTN_TOUCH / BTN_TOOL_FINGER 的值）。", ret="1 有触点；0 没有。",
    note="判的是来源状态里有触点，不是 iovec 里有没有 —— 虚拟触点抬起时不能把真手指的 BTN_TOUCH 带下去。"),
"emit_frame": dict(brief="把 phys[]/virt[] 合成一帧并提交：待抬 → 物理 → 虚拟 → BTN → SYN，整帧一次 writev。",
    ret="0 提交成功；-1 提交失败（置 g_reemit，由主循环重发）。",
    note="身份按下标算（物理 = i，虚拟 = phys_slots + i）；写失败绝不清 pending_up、绝不释放身份。"),
"set_virtual": dict(brief="改一个虚拟触点的状态（down/move/up）—— 单点命令与帧内命令共用这一段。",
    params=[("state", "virt[] 或 staged[]"), ("slot", "客户端槽号"), ("name", "\"down\"/\"move\"/\"up\""),
            ("x", "raw x"), ("y", "raw y")], ret="0 成功；-1 状态非法（重复 down、没 down 就 move/up）。",
    note="只改来源状态，不写身份字段（身份发射时按下标算）。"),
"owner_reset": dict(brief="客户端断连/被踢：抬掉它所有虚拟触点并立即提交一帧。",
    note="少了这段，客户端在 begin_frame..end_frame 中间断开会把虚拟手指永久粘在设备上。"),
"enqueue_phys_changes": dict(brief="物理帧边界之后：每槽比快照判 down/up/move，把变化入 region_q 喂区域线程（不推客户端）。",
    note="推的是「完整帧状态的快照」；静止不刷屏；必须在 emit_frame 之后调用（§4.1）。"),

# ---------------- §10 WebSocket ----------------
"rol32": dict(brief="32 位循环左移（SHA-1 内部用）。", params=[("x", "值"), ("n", "位数")], ret="左移结果。"),
"be32": dict(brief="读 4 字节大端整数（SHA-1 内部用）。", params=[("p", "字节指针")], ret="大端解读结果。"),
"sha1_block": dict(brief="处理一个 64 字节块（SHA-1 内部）。", params=[("s", "上下文"), ("p", "块起始")]),
"sha1_init": dict(brief="SHA-1 初始化。", params=[("s", "上下文")]),
"sha1_update": dict(brief="SHA-1 追加数据。", params=[("s", "上下文"), ("p", "数据"), ("n", "长度")]),
"sha1_final": dict(brief="SHA-1 收尾，输出 20 字节摘要（WS 握手用）。", params=[("s", "上下文"), ("out", "20 字节输出")]),
"base64": dict(brief="标准 Base64 编码。",
    params=[("in", "输入"), ("n", "输入长度"), ("out", "输出缓冲"), ("cap", "缓冲容量")],
    ret="写入的字节数（含结尾 \\0）；-1 缓冲不够。"),
"header_value": dict(brief="从 HTTP 请求头里取某个头的值（头名大小写不敏感）。",
    params=[("req", "请求原文"), ("name", "头名"), ("out", "输出"), ("cap", "缓冲容量")], ret="0 找到；-1 没有或缓冲不够。"),
"has_token": dict(brief="在请求头值里按逗号分词找 token（大小写不敏感，用于 Connection: Upgrade）。",
    params=[("s", "头值"), ("token", "要找的 token")], ret="1 有；0 没有。"),
"write_full": dict(brief="把 len 字节写满（EINTR、短写自动续写）。",
    params=[("fd", "目标 fd"), ("buf", "数据"), ("len", "长度")], ret="0 成功；-1 出错。",
    note="握手与上行同步写用它；下行的响应/事件走出站队列，不走这里。"),
"websocket_handshake": dict(brief="读 HTTP 请求、校验 Upgrade 与 Sec-WebSocket-Key，回 101。",
    params=[("fd", "已 accept 的连接")], ret="0 成功；-1 不是合法 WS 请求。", note="握手期用带超时的阻塞读（最多被拖 300ms）。"),
"ws_send": dict(brief="直接发一个 WS 帧（控制帧：close / pong 用）。",
    params=[("fd", "连接"), ("opcode", "操作码"), ("p", "正文"), ("n", "正文长度")], ret="0 成功；-1 失败。",
    note="只给控制帧用；文本帧请走 outq_push_text。"),
"drop_client": dict(brief="丢弃当前客户端：关连接 + 抬掉它的虚拟触点 + 清订阅位 + 清出站队列。",
    note="残留的订阅与残包不许串给下一个客户端（§4.6）。"),
"ws_peek_frame": dict(brief="试着从接收缓冲里解析出一个完整帧的表头。",
    params=[("frame_len", "输出整帧长度"), ("opcode", "输出操作码"), ("payload_off", "输出正文偏移")],
    ret="1 解析到；0 数据不够；-1 协议错。"),
"ws_next_frame": dict(brief="取出一个完整帧的正文（必要时继续收）。",
    params=[("payload", "输出正文"), ("plen", "输出长度"), ("opcode", "输出操作码")],
    ret="0 取到；1 暂时没有数据（EAGAIN）；-1 连接关闭或协议错。", note="半包不消费，留到下一轮 poll 继续拼。"),
"client_frame": dict(brief="处理客户端可读事件：一轮最多 32 个帧，解帧 → handle_line → 响应入出站队列。",
    ret="0 保持连接；-1 断开（协议错或连接关闭）。"),
"make_listen": dict(brief="建监听 socket，只绑 127.0.0.1（回环），不对外暴露。", ret="fd；-1 失败（调用方以退出码 6 退出）。"),
"cmd_meta": dict(brief="命令族：ping / res / reset（不碰触点的元命令）。",
    params=[("t", "命令词"), ("stp", "strtok_r 状态"), ("resp", "响应缓冲"), ("cap", "缓冲容量")],
    ret="1 不是本族命令（交给下一族）；0 / -1 = 已处理（-1 时 resp 是错误响应）。"),
"cmd_point_once": dict(brief="命令族：up / down / move —— 单点命令，每个命令提交一帧。",
    params=[("t", "命令词"), ("stp", "strtok_r 状态"), ("resp", "响应缓冲"), ("cap", "缓冲容量")],
    ret="1 不是本族命令；0 / -1 = 已处理（-1 时 resp 是错误响应）。"),
"cmd_frame": dict(brief="命令族：begin_frame / point / end_frame —— 帧内多点，一次 SYN 提交。",
    params=[("t", "命令词"), ("stp", "strtok_r 状态"), ("resp", "响应缓冲"), ("cap", "缓冲容量")],
    ret="1 不是本族命令；0 / -1 = 已处理（-1 时 resp 是错误响应）。"),
"cmd_region": dict(brief="命令族：region add | clear | list。",
    params=[("t", "命令词"), ("stp", "strtok_r 状态"), ("resp", "响应缓冲"), ("cap", "缓冲容量")],
    ret="1 不是本族命令；0 / -1 = 已处理（-1 时 resp 是错误响应）。", note="主线程只写表（短锁），判定全在区域线程。"),
"cmd_sub": dict(brief="命令族：sub [phys|region|all] / unsub（裸 sub = 两个通道都订）。",
    params=[("t", "命令词"), ("stp", "strtok_r 状态"), ("resp", "响应缓冲"), ("cap", "缓冲容量")],
    ret="1 不是本族命令；0 / -1 = 已处理（-1 时 resp 是错误响应）。"),
"handle_line": dict(brief="一行命令 → 一行回包：按命令族分派（每族一个 cmd_* 函数）。",
    params=[("line", "命令文本（原地改）"), ("resp", "响应缓冲"), ("cap", "缓冲容量")], ret="0 有响应；-1 错误响应。",
    note="响应文本拼进 resp，由调用方（client_frame）入出站队列。"),

# ---------------- §11 进程 ----------------
"apply_args": dict(brief="解析命令行：-w 宽 -h 高（可选，不给就自动探测）、-p 端口、-v 虚拟槽数。",
    params=[("argc", "参数个数"), ("argv", "参数数组")], note="取值越界会打日志并保留默认值。"),
"vtouch_init": dict(brief="初始化：锚墙钟 → 尺寸门 → 清表 → 认设备 → 建 uinput → 先起监听 → 最后 EVIOCGRAB → 起区域线程。",
    params=[("argc", "参数个数"), ("argv", "参数数组")], ret="0 成功；负数 = 失败阶段（-2..-7），main 直接拿它当退出码。",
    note="这个顺序是有意的：任何失败路径都不会留下「抓着触摸却没人能控制」的状态。"),
"vtouch_poll_step": dict(brief="主循环一轮：poll 四路 fd（物理 / 监听 / 客户端 / 出站）→ 各自处理 → 唯一刷出点。",
    ret="0 继续；-1 该退出。", note="有待重发的整帧时 poll 超时压到 5ms，尽快把手指抬起来。"),
"cleanup": dict(brief="释放资源：关客户端 → 关监听 → 放 EVIOCGRAB → 关设备。",
    note="逆序释放：先放触摸（物理触摸立刻回系统），再拆设备。"),
"ws_input_reset": dict(brief="复位 WS 输入缓冲（新客户端接入前清掉上一个客户端的残包）。"),
"ws_has_pending": dict(brief="WS 输入缓冲里是否还有没解析完的半包数据（主循环据此继续挂 POLLIN）。", ret="1 有；0 没有。",
    note="半包不消费：解析不出完整帧就留着，等下一轮 poll 再拼。"),
"on_signal": dict(brief="信号处理器：置退出标志，让主循环下一轮自己收尾（不在信号里做清理）。",
    params=[("s", "信号编号")], note="只置标志，不打印、不关 fd —— 信号处理函数里能做的事越少越安全。"),
"main": dict(brief="进程入口：装信号 → init → 主循环 → 置 stop_flag 并 join 区域线程 → cleanup。",
    params=[("argc", "参数个数"), ("argv", "参数数组")], ret="0；init 失败时返回对应的错误码。"),
}
